[package]
name = "hydr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4.24", features = ["serde"]}
serde = {version = "1.0.158", features = ["derive"]}
serde_yaml = "0.9.19"
termion = "2.0.1"
